#!/usr/bin/env bash
# regen-l1.sh — Auto-regenerate wiki/L1.md navigation index
# Scans wiki/projects/ and wiki/cards/ for tags + filenames,
# groups by scene categories, picks top notes per category.
#
# Usage: bash wiki/scripts/regen-l1.sh [--dry-run]
# Inspired by OpenViking SemanticProcessor auto-index pattern.

set -euo pipefail
WIKI_DIR="$(cd "$(dirname "$0")/.." && pwd)"
L1="$WIKI_DIR/L1.md"
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

NOW=$(date +%s)
TMP=$(mktemp /tmp/regen-l1.XXXXXX)
trap 'rm -f "$TMP"' EXIT

# ── Step 1: Build index of all notes ──
# Output to TMP: subdir/slug \t tags \t status \t age_days
for dir in "$WIKI_DIR/projects" "$WIKI_DIR/cards"; do
  subdir=$(basename "$dir")
  for f in "$dir"/*.md; do
    [[ -f "$f" ]] || continue
    slug=$(basename "$f" .md)
    mtime=$(stat -c %Y "$f" 2>/dev/null || echo "$NOW")
    age_days=$(( (NOW - mtime) / 86400 ))

    # Extract tags and status from YAML frontmatter
    tags=""
    status=""
    if head -1 "$f" | grep -q '^---$'; then
      tags=$(awk '/^---$/{n++; next} n==1 && /^tags:/{gsub(/[\[\]]/,""); sub(/^tags: */, ""); print; exit}' "$f")
      status=$(awk '/^---$/{n++; next} n==1 && /^status:/{sub(/^status: */, ""); print; exit}' "$f")
    fi

    # Wikilink count (lines containing wikilinks)
    wlinks=$(grep -c '\[\[' "$f" 2>/dev/null || true)
    [[ -z "$wlinks" || ! "$wlinks" =~ ^[0-9]+$ ]] && wlinks=0

    printf '%s/%s\t%s\t%s\t%d\t%d\n' "$subdir" "$slug" "$tags" "$status" "$age_days" "$wlinks" >> "$TMP"
  done
done

echo "📊 Indexed $(wc -l < "$TMP") notes" >&2

# ── Step 2: Category matching + scoring ──
# Each category: display text, then grep patterns for tags+slugs
generate_pointers() {
  local display="$1"
  shift
  # remaining args are grep -iE patterns to match against "slug tags" combined

  local results=""
  while IFS=$'\t' read -r path tags status age_days wlinks; do
    local combined="$path $tags"
    local matched=false
    for pat in "$@"; do
      if echo "$combined" | grep -qiE "$pat"; then
        matched=true
        break
      fi
    done
    $matched || continue

    # Score
    local score=1
    case "$status" in
      active) score=3 ;;
      tracking|monitor) score=2 ;;
    esac
    (( age_days <= 14 )) && score=$((score + 2))
    (( age_days > 14 && age_days <= 30 )) && score=$((score + 1))
    (( wlinks >= 5 )) && score=$((score + 1))

    results="${results}${score}|${path}\n"
  done < "$TMP"

  if [[ -n "$results" ]]; then
    # Sort by score desc, deduplicate, take top 4
    local top
    top=$(printf '%b' "$results" | sort -t'|' -k1 -rn | head -4 | cut -d'|' -f2 | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')
    echo "- ${display} → ${top}"
  fi
}

# ── Step 3: Generate output ──
{
cat <<'HEADER'
# L1 — Wiki Navigation Index (≤30 lines)

> Auto-generated by wiki/scripts/regen-l1.sh
> Existence encoding: tell the LLM knowledge EXISTS and WHERE. Not summaries.
> Hard cap: 30 lines. Every pointer must earn its slot.

## Rules (not in AGENTS.md — violating = wrong behavior)
- wiki 写完必须加 wikilinks 连接相关笔记（孤立笔记 = 死笔记）
- 新 wiki 写之前先搜已有笔记，避免重复（INDEX.md / rg）
- Track 类 TODO 到期不续就删，不无限延期

## Pointers (scene → knowledge)
HEADER

generate_pointers "agent 自进化/dreaming" \
  "self-evolv" "dreaming" "evolution" "gradient" "belief" "evolver" "genericagent" "mechanism-vs-evolution"

generate_pointers "打工选题/PR" \
  "contribution" "pr-review" "open-source" "gogetajob"

generate_pointers "记忆架构" \
  "agent-memory" "memory-.*taxon" "memory-.*landscape" "write-read-gap" "memory-volume" "recall"

generate_pointers "skill 设计/标准" \
  "agentskills" "skill-ecosystem" "skillclaw" "skill-context" "skill.*standard"

generate_pointers "安全/权限" \
  "agent-safety" "agent-security" "agent-credential" "action-authorization" "authorization"

generate_pointers "身份/DNA/信念" \
  "agent-identity" "self-construction" "self-portrait" "belief-system" "identity-protocol"

generate_pointers "OpenClaw 架构" \
  "openclaw" "acp" "gateway"

generate_pointers "竞品/生态" \
  "landscape" "hermes-agent" "mercury-agent" "agent-ecosystem"

generate_pointers "context 优化" \
  "context-budget" "thin-harness" "conciseness" "context-compact" "token-optim"

generate_pointers "编码品质/工作流" \
  "over-editing" "code-quality" "structural-backpressure" "dirac"

generate_pointers "工具/基建" \
  "agentic-stack" "mirage" "ironcurtain" "infrastructure" "mcp-"

} > /tmp/l1-candidate.md

LINES=$(wc -l < /tmp/l1-candidate.md)
echo "📝 Generated ${LINES} lines" >&2

if $DRY_RUN; then
  cat /tmp/l1-candidate.md
  echo "" >&2
  echo "--- dry run: ${LINES} lines ---" >&2
else
  cp /tmp/l1-candidate.md "$L1"
  echo "✅ L1.md regenerated (${LINES} lines)" >&2
fi
